name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install all dependencies
        run: npm install

      - name: executing tests
        run: npm run test:unit

      - name: Build production application
        run: npm run build

      - uses: crazy-max/ghaction-github-pages@v2.2.0
        name: Deploying to github pages
        with:
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
