name: Pull Request Workflow

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install all dependencies
        run: npm install

      - name: Build production application
        run: npm run build

      - name: executing tests
        run: npm run test:unit

      
